// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Galaxy.Web.API.Postman.Data.Entities;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Galaxy.Web.API.Postman.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Galaxy.Web.API.Postman.Data.Context
{
    public class AuthorConfiguration : IEntityTypeConfiguration<Author>
    {
        public void Configure(EntityTypeBuilder<Author> entity)
        {
            entity.ToTable("Author");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Genre)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        }
    }
}
