// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Galaxy.Web.API.Postman.Data.Entities;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Galaxy.Web.API.Postman.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Galaxy.Web.API.Postman.Data.Context
{
    public class BookConfiguration : IEntityTypeConfiguration<Book>
    {
        public void Configure(EntityTypeBuilder<Book> entity)
        {
            entity.ToTable("Book");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Title)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Author)
                .WithMany(p => p.Books)
                .HasForeignKey(d => d.AuthorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Book_Author");
        }
    }
}
