// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RealTimeApplication.API.Infrastructure.Data.Entities
{
    public partial class Tracking
    {
        public Tracking()
        {
            TrackingProducts = new HashSet<TrackingProduct>();
        }

        public int TrackingId { get; set; }
        public int OrderId { get; set; }
        public DateTime EstimatedDeliveryTime { get; set; }
        public int TrackingStatusId { get; set; }

        public virtual Order Order { get; set; }
        public virtual TrackingStatus TrackingStatus { get; set; }
        public virtual ICollection<TrackingProduct> TrackingProducts { get; set; }
    }
}