// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RealTimeApplication.API.Infrastructure.Data.Entities
{
    public partial class TrackingProduct
    {
        public int TrackingProductId { get; set; }
        public int TrackingId { get; set; }
        public int ProductId { get; set; }

        public virtual Product Product { get; set; }
        public virtual Tracking Tracking { get; set; }
    }
}