// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RealTimeApplication.API.Infrastructure.Data.Entities
{
    public partial class TrackingStatus
    {
        public TrackingStatus()
        {
            Trackings = new HashSet<Tracking>();
        }

        public int TrackingStatusId { get; set; }
        public string Description { get; set; }
        public string IconCls { get; set; }

        public virtual ICollection<Tracking> Trackings { get; set; }
    }
}