// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using RealTimeApplication.API.Infrastructure.Data.Entities;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using RealTimeApplication.API.Infrastructure.Data.Entities;

namespace RealTimeApplication.API.Infrastructure.Data.Contexts
{
    public partial class RealtimeapplicationContext : DbContext
    {
        public RealtimeapplicationContext()
        {
        }

        public RealtimeapplicationContext(DbContextOptions<RealtimeapplicationContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Tracking> Trackings { get; set; }
        public virtual DbSet<TrackingProduct> TrackingProducts { get; set; }
        public virtual DbSet<TrackingStatus> TrackingStatuses { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new ClientConfiguration());
            modelBuilder.ApplyConfiguration(new OrderConfiguration());
            modelBuilder.ApplyConfiguration(new ProductConfiguration());
            modelBuilder.ApplyConfiguration(new TrackingConfiguration());
            modelBuilder.ApplyConfiguration(new TrackingProductConfiguration());
            modelBuilder.ApplyConfiguration(new TrackingStatusConfiguration());


            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
